[package]
name = "battery_reminder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4"
battery = "0.7.8"
spin_sleep = "1.0.0"